env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:jsx-a11y/recommended"
  - "plugin:import/recommended"
  - "plugin:import/typescript"
  # - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - import
  - simple-import-sort
  - prettier
rules:
  prettier/prettier: warn
  simple-import-sort/imports: warn
  simple-import-sort/exports: warn
  "@typescript-eslint/explicit-module-boundary-types": off
